# Generated by Django 5.0 on 2023-12-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_food_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
