# Generated by Django 5.0 on 2024-02-18 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_history_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='users',
            new_name='user',
        ),
    ]
