# Generated by Django 5.0 on 2024-02-23 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_users_history_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
