# Generated by Django 5.0 on 2024-03-04 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_food_name_historyorderitem_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='food',
            new_name='item',
        ),
    ]
