# Generated by Django 5.0 on 2023-12-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_food_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='desc',
            field=models.TextField(max_length=500),
        ),
    ]
