# Generated by Django 5.0 on 2024-02-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_history_total_amount_remove_history_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='orders',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='food_items',
            new_name='order_items',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
