# Generated by Django 5.0 on 2024-03-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_food_orderitem_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyorderitem',
            old_name='name',
            new_name='food_name',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='name',
            new_name='food_name',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='food',
        ),
    ]
