# Generated by Django 5.0 on 2024-02-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_orders_history_order_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food',
            new_name='MenuItem',
        ),
    ]
