# Generated by Django 5.0 on 2024-03-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_history_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.IntegerField()),
                ('totalusers', models.IntegerField()),
                ('totalorders', models.IntegerField()),
            ],
        ),
    ]
