# Generated by Django 5.0 on 2024-03-09 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_salesreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreport',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesreport',
            name='profit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
