# Generated by Django 5.0 on 2024-02-25 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_history_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='order_items',
        ),
        migrations.CreateModel(
            name='HistoryOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.history')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.orderitem')),
            ],
        ),
    ]
