# Generated by Django 5.0 on 2024-02-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_history_order_items_historyorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='total_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
