# Generated by Django 5.0 on 2024-02-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_history_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyorderitem',
            name='order_item',
        ),
        migrations.AddField(
            model_name='historyorderitem',
            name='food_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
